/**
 * transfer_money
 * An API depicting the working of EKO platform
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 1.0.15
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.TransferMoney);
  }
}(this, function(expect, TransferMoney) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new TransferMoney.InlineResponse2001Parameters();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('InlineResponse2001Parameters', function() {
    it('should create an instance of InlineResponse2001Parameters', function() {
      // uncomment below and update the code to test InlineResponse2001Parameters
      //var instane = new TransferMoney.InlineResponse2001Parameters();
      //expect(instance).to.be.a(TransferMoney.InlineResponse2001Parameters);
    });

    it('should have the property recipientAccountNumber (base name: "recipient_account_number")', function() {
      // uncomment below and update the code to test the property recipientAccountNumber
      //var instane = new TransferMoney.InlineResponse2001Parameters();
      //expect(instance).to.be();
    });

    it('should have the property recipientId (base name: "recipient_id")', function() {
      // uncomment below and update the code to test the property recipientId
      //var instane = new TransferMoney.InlineResponse2001Parameters();
      //expect(instance).to.be();
    });

    it('should have the property recipientName (base name: "recipient_name")', function() {
      // uncomment below and update the code to test the property recipientName
      //var instane = new TransferMoney.InlineResponse2001Parameters();
      //expect(instance).to.be();
    });

  });

}));
