/**
 * transfer_money
 * An API depicting the working of EKO platform
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 1.0.15
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.TransferMoney);
  }
}(this, function(expect, TransferMoney) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new TransferMoney.InlineResponse20011Data();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('InlineResponse20011Data', function() {
    it('should create an instance of InlineResponse20011Data', function() {
      // uncomment below and update the code to test InlineResponse20011Data
      //var instane = new TransferMoney.InlineResponse20011Data();
      //expect(instance).to.be.a(TransferMoney.InlineResponse20011Data);
    });

    it('should have the property isVerificationAvailable (base name: "isVerificationAvailable")', function() {
      // uncomment below and update the code to test the property isVerificationAvailable
      //var instane = new TransferMoney.InlineResponse20011Data();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instane = new TransferMoney.InlineResponse20011Data();
      //expect(instance).to.be();
    });

    it('should have the property ifscStatus (base name: "ifsc_status")', function() {
      // uncomment below and update the code to test the property ifscStatus
      //var instane = new TransferMoney.InlineResponse20011Data();
      //expect(instance).to.be();
    });

    it('should have the property availableChannels (base name: "available_channels")', function() {
      // uncomment below and update the code to test the property availableChannels
      //var instane = new TransferMoney.InlineResponse20011Data();
      //expect(instance).to.be();
    });

    it('should have the property code (base name: "code")', function() {
      // uncomment below and update the code to test the property code
      //var instane = new TransferMoney.InlineResponse20011Data();
      //expect(instance).to.be();
    });

  });

}));
