/**
 * transfer_money
 * An API depicting the working of EKO platform
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 1.0.15
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.TransferMoney) {
      root.TransferMoney = {};
    }
    root.TransferMoney.InlineResponse2007Data = factory(root.TransferMoney.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The InlineResponse2007Data model module.
   * @module model/InlineResponse2007Data
   * @version 0.0.1
   */

  /**
   * Constructs a new <code>InlineResponse2007Data</code>.
   * @alias module:model/InlineResponse2007Data
   * @class
   */
  var exports = function() {
    var _this = this;
















  };

  /**
   * Constructs a <code>InlineResponse2007Data</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/InlineResponse2007Data} obj Optional instance to populate.
   * @return {module:model/InlineResponse2007Data} The populated <code>InlineResponse2007Data</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('timestamp')) {
        obj['timestamp'] = ApiClient.convertToType(data['timestamp'], 'Date');
      }
      if (data.hasOwnProperty('tx_status')) {
        obj['tx_status'] = ApiClient.convertToType(data['tx_status'], 'String');
      }
      if (data.hasOwnProperty('txstatus_desc')) {
        obj['txstatus_desc'] = ApiClient.convertToType(data['txstatus_desc'], 'String');
      }
      if (data.hasOwnProperty('debit_user_id')) {
        obj['debit_user_id'] = ApiClient.convertToType(data['debit_user_id'], 'String');
      }
      if (data.hasOwnProperty('balance')) {
        obj['balance'] = ApiClient.convertToType(data['balance'], 'String');
      }
      if (data.hasOwnProperty('fee')) {
        obj['fee'] = ApiClient.convertToType(data['fee'], 'String');
      }
      if (data.hasOwnProperty('amount')) {
        obj['amount'] = ApiClient.convertToType(data['amount'], 'String');
      }
      if (data.hasOwnProperty('state')) {
        obj['state'] = ApiClient.convertToType(data['state'], 'String');
      }
      if (data.hasOwnProperty('recipient_id')) {
        obj['recipient_id'] = ApiClient.convertToType(data['recipient_id'], 'String');
      }
      if (data.hasOwnProperty('service_tax')) {
        obj['service_tax'] = ApiClient.convertToType(data['service_tax'], 'String');
      }
      if (data.hasOwnProperty('transaction_id')) {
        obj['transaction_id'] = ApiClient.convertToType(data['transaction_id'], 'String');
      }
      if (data.hasOwnProperty('customer_id')) {
        obj['customer_id'] = ApiClient.convertToType(data['customer_id'], 'String');
      }
      if (data.hasOwnProperty('channel')) {
        obj['channel'] = ApiClient.convertToType(data['channel'], 'String');
      }
      if (data.hasOwnProperty('currency')) {
        obj['currency'] = ApiClient.convertToType(data['currency'], 'String');
      }
      if (data.hasOwnProperty('client_ref_id')) {
        obj['client_ref_id'] = ApiClient.convertToType(data['client_ref_id'], 'Number');
      }
    }
    return obj;
  }

  /**
   * @member {Date} timestamp
   */
  exports.prototype['timestamp'] = undefined;
  /**
   * @member {String} tx_status
   */
  exports.prototype['tx_status'] = undefined;
  /**
   * @member {String} txstatus_desc
   */
  exports.prototype['txstatus_desc'] = undefined;
  /**
   * @member {String} debit_user_id
   */
  exports.prototype['debit_user_id'] = undefined;
  /**
   * @member {String} balance
   */
  exports.prototype['balance'] = undefined;
  /**
   * @member {String} fee
   */
  exports.prototype['fee'] = undefined;
  /**
   * @member {String} amount
   */
  exports.prototype['amount'] = undefined;
  /**
   * @member {String} state
   */
  exports.prototype['state'] = undefined;
  /**
   * @member {String} recipient_id
   */
  exports.prototype['recipient_id'] = undefined;
  /**
   * @member {String} service_tax
   */
  exports.prototype['service_tax'] = undefined;
  /**
   * @member {String} transaction_id
   */
  exports.prototype['transaction_id'] = undefined;
  /**
   * @member {String} customer_id
   */
  exports.prototype['customer_id'] = undefined;
  /**
   * @member {String} channel
   */
  exports.prototype['channel'] = undefined;
  /**
   * @member {String} currency
   */
  exports.prototype['currency'] = undefined;
  /**
   * @member {Number} client_ref_id
   */
  exports.prototype['client_ref_id'] = undefined;



  return exports;
}));


