/**
 * transfer_money
 * An API depicting the working of EKO platform
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 1.0.15
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.TransferMoney) {
      root.TransferMoney = {};
    }
    root.TransferMoney.InlineResponse20011Data = factory(root.TransferMoney.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The InlineResponse20011Data model module.
   * @module model/InlineResponse20011Data
   * @version 0.0.1
   */

  /**
   * Constructs a new <code>InlineResponse20011Data</code>.
   * @alias module:model/InlineResponse20011Data
   * @class
   */
  var exports = function() {
    var _this = this;






  };

  /**
   * Constructs a <code>InlineResponse20011Data</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/InlineResponse20011Data} obj Optional instance to populate.
   * @return {module:model/InlineResponse20011Data} The populated <code>InlineResponse20011Data</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('isVerificationAvailable')) {
        obj['isVerificationAvailable'] = ApiClient.convertToType(data['isVerificationAvailable'], 'String');
      }
      if (data.hasOwnProperty('name')) {
        obj['name'] = ApiClient.convertToType(data['name'], 'String');
      }
      if (data.hasOwnProperty('ifsc_status')) {
        obj['ifsc_status'] = ApiClient.convertToType(data['ifsc_status'], 'Number');
      }
      if (data.hasOwnProperty('available_channels')) {
        obj['available_channels'] = ApiClient.convertToType(data['available_channels'], 'Number');
      }
      if (data.hasOwnProperty('code')) {
        obj['code'] = ApiClient.convertToType(data['code'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {String} isVerificationAvailable
   */
  exports.prototype['isVerificationAvailable'] = undefined;
  /**
   * @member {String} name
   */
  exports.prototype['name'] = undefined;
  /**
   * @member {Number} ifsc_status
   */
  exports.prototype['ifsc_status'] = undefined;
  /**
   * @member {Number} available_channels
   */
  exports.prototype['available_channels'] = undefined;
  /**
   * @member {String} code
   */
  exports.prototype['code'] = undefined;



  return exports;
}));


