/**
 * transfer_money
 * An API depicting the working of EKO platform
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 1.0.15
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.TransferMoney) {
      root.TransferMoney = {};
    }
    root.TransferMoney.InlineResponse2005Data = factory(root.TransferMoney.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The InlineResponse2005Data model module.
   * @module model/InlineResponse2005Data
   * @version 0.0.1
   */

  /**
   * Constructs a new <code>InlineResponse2005Data</code>.
   * @alias module:model/InlineResponse2005Data
   * @class
   */
  var exports = function() {
    var _this = this;






  };

  /**
   * Constructs a <code>InlineResponse2005Data</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/InlineResponse2005Data} obj Optional instance to populate.
   * @return {module:model/InlineResponse2005Data} The populated <code>InlineResponse2005Data</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('recipient_id_type')) {
        obj['recipient_id_type'] = ApiClient.convertToType(data['recipient_id_type'], 'String');
      }
      if (data.hasOwnProperty('name')) {
        obj['name'] = ApiClient.convertToType(data['name'], 'String');
      }
      if (data.hasOwnProperty('recipient_id')) {
        obj['recipient_id'] = ApiClient.convertToType(data['recipient_id'], 'Number');
      }
      if (data.hasOwnProperty('account')) {
        obj['account'] = ApiClient.convertToType(data['account'], 'String');
      }
      if (data.hasOwnProperty('ifsc')) {
        obj['ifsc'] = ApiClient.convertToType(data['ifsc'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {String} recipient_id_type
   */
  exports.prototype['recipient_id_type'] = undefined;
  /**
   * @member {String} name
   */
  exports.prototype['name'] = undefined;
  /**
   * @member {Number} recipient_id
   */
  exports.prototype['recipient_id'] = undefined;
  /**
   * @member {String} account
   */
  exports.prototype['account'] = undefined;
  /**
   * @member {String} ifsc
   */
  exports.prototype['ifsc'] = undefined;



  return exports;
}));


