/**
 * transfer_money
 * An API depicting the working of EKO platform
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 1.0.15
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/InlineResponse2001Parameters'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./InlineResponse2001Parameters'));
  } else {
    // Browser globals (root is window)
    if (!root.TransferMoney) {
      root.TransferMoney = {};
    }
    root.TransferMoney.InlineResponse2001 = factory(root.TransferMoney.ApiClient, root.TransferMoney.InlineResponse2001Parameters);
  }
}(this, function(ApiClient, InlineResponse2001Parameters) {
  'use strict';




  /**
   * The InlineResponse2001 model module.
   * @module model/InlineResponse2001
   * @version 0.0.1
   */

  /**
   * Constructs a new <code>InlineResponse2001</code>.
   * @alias module:model/InlineResponse2001
   * @class
   */
  var exports = function() {
    var _this = this;







  };

  /**
   * Constructs a <code>InlineResponse2001</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/InlineResponse2001} obj Optional instance to populate.
   * @return {module:model/InlineResponse2001} The populated <code>InlineResponse2001</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('response_type_id')) {
        obj['response_type_id'] = ApiClient.convertToType(data['response_type_id'], 'String');
      }
      if (data.hasOwnProperty('end_note')) {
        obj['end_note'] = ApiClient.convertToType(data['end_note'], 'String');
      }
      if (data.hasOwnProperty('response_status_id')) {
        obj['response_status_id'] = ApiClient.convertToType(data['response_status_id'], 'String');
      }
      if (data.hasOwnProperty('parameters')) {
        obj['parameters'] = InlineResponse2001Parameters.constructFromObject(data['parameters']);
      }
      if (data.hasOwnProperty('unique_reference_id')) {
        obj['unique_reference_id'] = ApiClient.convertToType(data['unique_reference_id'], 'String');
      }
      if (data.hasOwnProperty('salutation')) {
        obj['salutation'] = ApiClient.convertToType(data['salutation'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {String} response_type_id
   */
  exports.prototype['response_type_id'] = undefined;
  /**
   * @member {String} end_note
   */
  exports.prototype['end_note'] = undefined;
  /**
   * @member {String} response_status_id
   */
  exports.prototype['response_status_id'] = undefined;
  /**
   * @member {module:model/InlineResponse2001Parameters} parameters
   */
  exports.prototype['parameters'] = undefined;
  /**
   * @member {String} unique_reference_id
   */
  exports.prototype['unique_reference_id'] = undefined;
  /**
   * @member {String} salutation
   */
  exports.prototype['salutation'] = undefined;



  return exports;
}));


