/**
 * transfer_money
 * An API depicting the working of EKO platform
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 1.0.15
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.TransferMoney) {
      root.TransferMoney = {};
    }
    root.TransferMoney.InlineResponse2009Data = factory(root.TransferMoney.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The InlineResponse2009Data model module.
   * @module model/InlineResponse2009Data
   * @version 0.0.1
   */

  /**
   * Constructs a new <code>InlineResponse2009Data</code>.
   * @alias module:model/InlineResponse2009Data
   * @class
   */
  var exports = function() {
    var _this = this;










  };

  /**
   * Constructs a <code>InlineResponse2009Data</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/InlineResponse2009Data} obj Optional instance to populate.
   * @return {module:model/InlineResponse2009Data} The populated <code>InlineResponse2009Data</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('refunded_amount')) {
        obj['refunded_amount'] = ApiClient.convertToType(data['refunded_amount'], 'String');
      }
      if (data.hasOwnProperty('timestamp')) {
        obj['timestamp'] = ApiClient.convertToType(data['timestamp'], 'String');
      }
      if (data.hasOwnProperty('fee')) {
        obj['fee'] = ApiClient.convertToType(data['fee'], 'String');
      }
      if (data.hasOwnProperty('amount')) {
        obj['amount'] = ApiClient.convertToType(data['amount'], 'String');
      }
      if (data.hasOwnProperty('state')) {
        obj['state'] = ApiClient.convertToType(data['state'], 'String');
      }
      if (data.hasOwnProperty('service_tax')) {
        obj['service_tax'] = ApiClient.convertToType(data['service_tax'], 'String');
      }
      if (data.hasOwnProperty('tid')) {
        obj['tid'] = ApiClient.convertToType(data['tid'], 'String');
      }
      if (data.hasOwnProperty('client_ref_id')) {
        obj['client_ref_id'] = ApiClient.convertToType(data['client_ref_id'], 'Number');
      }
      if (data.hasOwnProperty('refund_tid')) {
        obj['refund_tid'] = ApiClient.convertToType(data['refund_tid'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {String} refunded_amount
   */
  exports.prototype['refunded_amount'] = undefined;
  /**
   * @member {String} timestamp
   */
  exports.prototype['timestamp'] = undefined;
  /**
   * @member {String} fee
   */
  exports.prototype['fee'] = undefined;
  /**
   * @member {String} amount
   */
  exports.prototype['amount'] = undefined;
  /**
   * @member {String} state
   */
  exports.prototype['state'] = undefined;
  /**
   * @member {String} service_tax
   */
  exports.prototype['service_tax'] = undefined;
  /**
   * @member {String} tid
   */
  exports.prototype['tid'] = undefined;
  /**
   * @member {Number} client_ref_id
   */
  exports.prototype['client_ref_id'] = undefined;
  /**
   * @member {String} refund_tid
   */
  exports.prototype['refund_tid'] = undefined;



  return exports;
}));


