/**
 * transfer_money
 * An API depicting the working of EKO platform
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 1.0.15
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.TransferMoney) {
      root.TransferMoney = {};
    }
    root.TransferMoney.InlineResponse2006Data = factory(root.TransferMoney.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The InlineResponse2006Data model module.
   * @module model/InlineResponse2006Data
   * @version 0.0.1
   */

  /**
   * Constructs a new <code>InlineResponse2006Data</code>.
   * @alias module:model/InlineResponse2006Data
   * @class
   */
  var exports = function() {
    var _this = this;






  };

  /**
   * Constructs a <code>InlineResponse2006Data</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/InlineResponse2006Data} obj Optional instance to populate.
   * @return {module:model/InlineResponse2006Data} The populated <code>InlineResponse2006Data</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('recipient_id_type')) {
        obj['recipient_id_type'] = ApiClient.convertToType(data['recipient_id_type'], 'String');
      }
      if (data.hasOwnProperty('recipient_id')) {
        obj['recipient_id'] = ApiClient.convertToType(data['recipient_id'], 'Number');
      }
      if (data.hasOwnProperty('recipient_mobile')) {
        obj['recipient_mobile'] = ApiClient.convertToType(data['recipient_mobile'], 'String');
      }
      if (data.hasOwnProperty('customer_id')) {
        obj['customer_id'] = ApiClient.convertToType(data['customer_id'], 'String');
      }
      if (data.hasOwnProperty('is_self_account')) {
        obj['is_self_account'] = ApiClient.convertToType(data['is_self_account'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {String} recipient_id_type
   */
  exports.prototype['recipient_id_type'] = undefined;
  /**
   * @member {Number} recipient_id
   */
  exports.prototype['recipient_id'] = undefined;
  /**
   * @member {String} recipient_mobile
   */
  exports.prototype['recipient_mobile'] = undefined;
  /**
   * @member {String} customer_id
   */
  exports.prototype['customer_id'] = undefined;
  /**
   * @member {String} is_self_account
   */
  exports.prototype['is_self_account'] = undefined;



  return exports;
}));


