/**
 * transfer_money
 * An API depicting the working of EKO platform
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 1.0.15
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.TransferMoney) {
      root.TransferMoney = {};
    }
    root.TransferMoney.InlineResponse20013Data = factory(root.TransferMoney.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The InlineResponse20013Data model module.
   * @module model/InlineResponse20013Data
   * @version 0.0.1
   */

  /**
   * Constructs a new <code>InlineResponse20013Data</code>.
   * @alias module:model/InlineResponse20013Data
   * @class
   */
  var exports = function() {
    var _this = this;











  };

  /**
   * Constructs a <code>InlineResponse20013Data</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/InlineResponse20013Data} obj Optional instance to populate.
   * @return {module:model/InlineResponse20013Data} The populated <code>InlineResponse20013Data</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('account')) {
        obj['account'] = ApiClient.convertToType(data['account'], 'String');
      }
      if (data.hasOwnProperty('bank')) {
        obj['bank'] = ApiClient.convertToType(data['bank'], 'String');
      }
      if (data.hasOwnProperty('receipient_name')) {
        obj['receipient_name'] = ApiClient.convertToType(data['receipient_name'], 'String');
      }
      if (data.hasOwnProperty('is_name_editable')) {
        obj['is_name_editable'] = ApiClient.convertToType(data['is_name_editable'], 'String');
      }
      if (data.hasOwnProperty('tid')) {
        obj['tid'] = ApiClient.convertToType(data['tid'], 'String');
      }
      if (data.hasOwnProperty('amount')) {
        obj['amount'] = ApiClient.convertToType(data['amount'], 'Number');
      }
      if (data.hasOwnProperty('fee')) {
        obj['fee'] = ApiClient.convertToType(data['fee'], 'Number');
      }
      if (data.hasOwnProperty('is_ifsc_required')) {
        obj['is_ifsc_required'] = ApiClient.convertToType(data['is_ifsc_required'], 'String');
      }
      if (data.hasOwnProperty('ifsc')) {
        obj['ifsc'] = ApiClient.convertToType(data['ifsc'], 'String');
      }
      if (data.hasOwnProperty('aadhar')) {
        obj['aadhar'] = ApiClient.convertToType(data['aadhar'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {String} account
   */
  exports.prototype['account'] = undefined;
  /**
   * @member {String} bank
   */
  exports.prototype['bank'] = undefined;
  /**
   * @member {String} receipient_name
   */
  exports.prototype['receipient_name'] = undefined;
  /**
   * @member {String} is_name_editable
   */
  exports.prototype['is_name_editable'] = undefined;
  /**
   * @member {String} tid
   */
  exports.prototype['tid'] = undefined;
  /**
   * @member {Number} amount
   */
  exports.prototype['amount'] = undefined;
  /**
   * @member {Number} fee
   */
  exports.prototype['fee'] = undefined;
  /**
   * @member {String} is_ifsc_required
   */
  exports.prototype['is_ifsc_required'] = undefined;
  /**
   * @member {String} ifsc
   */
  exports.prototype['ifsc'] = undefined;
  /**
   * @member {String} aadhar
   */
  exports.prototype['aadhar'] = undefined;



  return exports;
}));


