/**
 * transfer_money
 * An API depicting the working of EKO platform
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 1.0.15
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.TransferMoney);
  }
}(this, function(expect, TransferMoney) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new TransferMoney.CustomersApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('CustomersApi', function() {
    describe('customersCustomerIdTypecustomerIdGet', function() {
      it('should call customersCustomerIdTypecustomerIdGet successfully', function(done) {
        //uncomment below and update the code to test customersCustomerIdTypecustomerIdGet
        //instance.customersCustomerIdTypecustomerIdGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('customersCustomerIdTypecustomerIdOtpPut', function() {
      it('should call customersCustomerIdTypecustomerIdOtpPut successfully', function(done) {
        //uncomment below and update the code to test customersCustomerIdTypecustomerIdOtpPut
        //instance.customersCustomerIdTypecustomerIdOtpPut(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('customersCustomerIdTypecustomerIdPut', function() {
      it('should call customersCustomerIdTypecustomerIdPut successfully', function(done) {
        //uncomment below and update the code to test customersCustomerIdTypecustomerIdPut
        //instance.customersCustomerIdTypecustomerIdPut(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('customersVerificationOtpotpPut', function() {
      it('should call customersVerificationOtpotpPut successfully', function(done) {
        //uncomment below and update the code to test customersVerificationOtpotpPut
        //instance.customersVerificationOtpotpPut(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
