/**
 * transfer_money
 * An API depicting the working of EKO platform
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 1.0.15
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.TransferMoney);
  }
}(this, function(expect, TransferMoney) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new TransferMoney.RecipientsApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('RecipientsApi', function() {
    describe('customersCustomerIdTypecustomerIdRecipientsGet', function() {
      it('should call customersCustomerIdTypecustomerIdRecipientsGet successfully', function(done) {
        //uncomment below and update the code to test customersCustomerIdTypecustomerIdRecipientsGet
        //instance.customersCustomerIdTypecustomerIdRecipientsGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('customersCustomerIdTypecustomerIdRecipientsRecipientIdidGet', function() {
      it('should call customersCustomerIdTypecustomerIdRecipientsRecipientIdidGet successfully', function(done) {
        //uncomment below and update the code to test customersCustomerIdTypecustomerIdRecipientsRecipientIdidGet
        //instance.customersCustomerIdTypecustomerIdRecipientsRecipientIdidGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('customerscustomerIdTypecustomerIdRecipientsrecipientsIdTypeidPut', function() {
      it('should call customerscustomerIdTypecustomerIdRecipientsrecipientsIdTypeidPut successfully', function(done) {
        //uncomment below and update the code to test customerscustomerIdTypecustomerIdRecipientsrecipientsIdTypeidPut
        //instance.customerscustomerIdTypecustomerIdRecipientsrecipientsIdTypeidPut(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
